export const AUTH__LOGIN_SUCCESS = 'AUTH__LOGIN_SUCCESS';

export const AUTH__SIGNUP_SUCCESS = 'AUTH__SIGNUP_SUCCESS';

export const AUTH__GET_CURRENT_USER_SUCCESS = 'AUTH__GET_CURRENT_USER_SUCCESS';

export const AUTH__SAVE_CURRENT_USER_SUCCESS = 'AUTH__SAVE_CURRENT_USER_SUCCESS';
