export const AUTH__LOGIN_SUCCESS = 'AUTH__LOGIN_SUCCESS';
export const AUTH__LOGIN_ERROR = 'AUTH__LOGIN_ERROR';

export const AUTH__SIGNUP_SUCCESS = 'AUTH__SIGNUP_SUCCESS';
export const AUTH__SIGNUP_ERROR = 'AUTH__SIGNUP_ERROR';
