export const PROFILE__LOGIN_SUCCESS = 'PROFILE__LOGIN_SUCCESS';

export const PROFILE__LOGOUT = 'PROFILE__LOGOUT';

export const PROFILE__SIGNUP_SUCCESS = 'PROFILE__SIGNUP_SUCCESS';

export const PROFILE__GET_CURRENT_USER_SUCCESS = 'PROFILE__GET_CURRENT_USER_SUCCESS';

export const PROFILE__SAVE_CURRENT_USER_SUCCESS = 'PROFILE__SAVE_CURRENT_USER_SUCCESS';

export const PROFILE__FETCH_COACHINGS_SUCCESS = 'PROFILE__FETCH_COACHINGS_SUCCESS';

export const PROFILE__GET_COACHING_SUCCESS = 'PROFILE__GET_COACHING_SUCCESS';
export const PROFILE__CREATE_COACHING_SUCCESS = 'PROFILE__CREATE_COACHING_SUCCESS';
export const PROFILE__DELETE_COACHING_SUCCESS = 'PROFILE__DELETE_COACHING_SUCCESS';
